[master]
32.197.211.67 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ec2-user/adi-lab-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no' private_ip=172.31.3.67

[workers]
32.195.56.55 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ec2-user/adi-lab-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no' private_ip=172.31.13.146
3.235.86.0 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ec2-user/adi-lab-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no' private_ip=172.31.10.31

[k8s_cluster:children]
master
workers
